name: TDD JS Sample CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: tree
    - uses: actions/checkout@v2
      with: 
        persist-credentials: false
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
        cache-dependency-path: '/home/runner/work/TestGithubActions/TestGithubActions/.github/workflows/package-lock'
    - run: npm ci
    - run: npm test
